config {
  type: "test",
  dataset: "cleaned_pages"
}

input "raw_pages" {
  SELECT 'Alphabet_Inc.' AS raw_title UNION ALL
  SELECT 'Apple_Inc.' AS raw_title UNION ALL
  SELECT 'Microsoft' AS raw_title
}

SELECT 'Alphabet_Inc.' AS raw_title, 'Alphabet Inc.' AS clean_title UNION ALL
SELECT 'Apple_Inc.' AS raw_title, 'Apple Inc.' AS clean_title UNION ALL
SELECT 'Microsoft' AS raw_title, 'Microsoft' AS clean_title